[package]
name = "exercism/rna-transcription"
version = "0.1.0"
authors = []

[[targets.test]]
name = "test-rna-transcription"
main = "tests/RnaTranscriptionTest.idr"

[dependencies]

[dev_dependencies]
"pheymann/specdris" = { git = "https://github.com/pheymann/specdris" }

[targets.lib]
path = "src"
mods = [
    "RnaTranscription"
]
