[package]
name = "exercism/hamming"
version = "0.1.0"
authors = []

[[targets.test]]
name = "test-hamming"
main = "tests/HammingTest.idr"

[dependencies]

[dev_dependencies]
"pheymann/specdris" = { git = "https://github.com/pheymann/specdris" }

[targets.lib]
path = "src"
mods = [
    "Hamming"
]
