[package]
name = "exercism/leap"
version = "0.1.0"
authors = []

[[targets.test]]
name = "test-leap"
main = "tests/LeapTest.idr"

[dependencies]

[dev_dependencies]
"pheymann/specdris" = { git = "https://github.com/pheymann/specdris" }

[targets.lib]
path = "src"
mods = [
    "Leap"
]
